// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Account struct {
	UserID   int64  `json:"user_id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Demand struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Url         sql.NullString `json:"url"`
	Price       sql.NullString `json:"price"`
	Isdone      sql.NullString `json:"isdone"`
	AccountID   int64          `json:"account_id"`
}

type DemandTransfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	DemandID      int64 `json:"demand_id"`
}
